/**
 * playwrightScriptGenerator.js
 * Generates a @playwright/test compatible test script
 * based on discovered UI components and the test plan.
 */

function sanitize(str) {
  return (str || '').replace(/[`\\$"]/g, m => `\\${m}`).replace(/\n/g, ' ').substring(0, 80);
}

function jsString(str) {
  return `'${(str || '').replace(/'/g, "\\'")}'`;
}

function generatePlaywrightScript(url, components, testPlan) {
  const lines = [];
  const d = new Date().toISOString();

  // ── File header ────────────────────────────────────────────────────────────
  lines.push(`// ═══════════════════════════════════════════════════════════════`);
  lines.push(`//  Auto-generated Playwright Test Script`);
  lines.push(`//  Generated by: Web Automation testing tool v1.0.0`);
  lines.push(`//  Tester: Princia Vadlea`);
  lines.push(`//  Target URL  : ${url}`);
  lines.push(`//  Page Title  : ${sanitize(components.pageTitle)}`);
  lines.push(`//  Generated at: ${d}`);
  lines.push(`// ═══════════════════════════════════════════════════════════════`);
  lines.push(`//`);
  lines.push(`//  To run these tests:`);
  lines.push(`//    1. npm install @playwright/test`);
  lines.push(`//    2. npx playwright install chromium`);
  lines.push(`//    3. npx playwright test ui-tests.spec.js`);
  lines.push(`//`);
  lines.push(``);
  lines.push(`const { test, expect } = require('@playwright/test');`);
  lines.push(``);
  lines.push(`const BASE_URL = ${jsString(url)};`);
  lines.push(``);
  lines.push(`test.describe('Auto-generated UI Tests – ${sanitize(components.pageTitle)}', () => {`);
  lines.push(``);

  // ── beforeEach ─────────────────────────────────────────────────────────────
  lines.push(`  test.beforeEach(async ({ page }) => {`);
  lines.push(`    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });`);
  lines.push(`  });`);
  lines.push(``);

  // ── 1. Page Load Test ─────────────────────────────────────────────────────
  lines.push(`  // ── Page Load & Title ────────────────────────────────────────`);
  lines.push(`  test('Page loads successfully and has correct title', async ({ page }) => {`);
  lines.push(`    await expect(page).toHaveURL(BASE_URL);`);
  if (components.pageTitle && components.pageTitle !== '(no title)') {
    lines.push(`    const title = await page.title();`);
    lines.push(`    expect(title.length).toBeGreaterThan(0);`);
    lines.push(`    console.log('Page title:', title);`);
  }
  lines.push(`    // Verify no uncaught JS errors on page load`);
  lines.push(`    const errors = [];`);
  lines.push(`    page.on('pageerror', err => errors.push(err.message));`);
  lines.push(`    await page.reload();`);
  lines.push(`    expect(errors.length, 'No JS errors on page load').toBe(0);`);
  lines.push(`  });`);
  lines.push(``);

  // ── 2. Input Field Validation Tests ───────────────────────────────────────
  if (components.inputs.length > 0 || components.textareas.length > 0) {
    lines.push(`  // ── 3.1 Input Field Validation ──────────────────────────────`);

    components.inputs.slice(0, 10).forEach((input, i) => {
      const label = sanitize(input.label || input.name || input.placeholder || `input-${i}`);
      const selector = input.selector;
      const validValue = getValidValue(input.type);
      const invalidValue = getInvalidValue(input.type);

      lines.push(`  test('Input: "${label}" – accepts valid data', async ({ page }) => {`);
      lines.push(`    const field = page.locator(${jsString(selector)}).first();`);
      lines.push(`    await field.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
      lines.push(`    const isVisible = await field.isVisible().catch(() => false);`);
      lines.push(`    if (!isVisible) { test.skip(); return; }`);
      lines.push(`    await field.click();`);
      lines.push(`    await field.fill(${jsString(validValue)});`);
      lines.push(`    const value = await field.inputValue();`);
      lines.push(`    expect(value.length).toBeGreaterThan(0);`);
      lines.push(`  });`);
      lines.push(``);

      if (['email', 'tel', 'url', 'number'].includes(input.type)) {
        lines.push(`  test('Input: "${label}" – rejects invalid ${input.type} data', async ({ page }) => {`);
        lines.push(`    const field = page.locator(${jsString(selector)}).first();`);
        lines.push(`    await field.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
        lines.push(`    const isVisible = await field.isVisible().catch(() => false);`);
        lines.push(`    if (!isVisible) { test.skip(); return; }`);
        lines.push(`    await field.fill(${jsString(invalidValue)});`);
        lines.push(`    // Trigger validation via blur`);
        lines.push(`    await field.evaluate(el => el.blur());`);
        lines.push(`    // Check native validity`);
        lines.push(`    const isValid = await field.evaluate(el => el.checkValidity ? el.checkValidity() : true);`);
        lines.push(`    expect(isValid, 'Invalid ${input.type} should fail native validation').toBe(false);`);
        lines.push(`  });`);
        lines.push(``);
      }

      if (input.required) {
        lines.push(`  test('Input: "${label}" – required field cannot be empty', async ({ page }) => {`);
        lines.push(`    const field = page.locator(${jsString(selector)}).first();`);
        lines.push(`    await field.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
        lines.push(`    const isVisible = await field.isVisible().catch(() => false);`);
        lines.push(`    if (!isVisible) { test.skip(); return; }`);
        lines.push(`    await field.fill('');`);
        lines.push(`    const isRequired = await field.evaluate(el => el.required);`);
        lines.push(`    expect(isRequired, 'Field should be marked as required').toBe(true);`);
        lines.push(`  });`);
        lines.push(``);
      }
    });

    // Textareas
    components.textareas.slice(0, 5).forEach((ta, i) => {
      const label = sanitize(ta.label || ta.name || ta.placeholder || `textarea-${i}`);
      lines.push(`  test('Textarea: "${label}" – accepts multi-line input', async ({ page }) => {`);
      lines.push(`    const field = page.locator(${jsString(ta.selector)}).first();`);
      lines.push(`    await field.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
      lines.push(`    const isVisible = await field.isVisible().catch(() => false);`);
      lines.push(`    if (!isVisible) { test.skip(); return; }`);
      lines.push(`    const multilineText = 'Line one\\nLine two\\nLine three';`);
      lines.push(`    await field.fill(multilineText);`);
      lines.push(`    const value = await field.inputValue();`);
      lines.push(`    expect(value).toContain('Line one');`);
      lines.push(`    expect(value).toContain('Line two');`);
      lines.push(`  });`);
      lines.push(``);
    });
  }

  // ── 3. Dropdown Tests ─────────────────────────────────────────────────────
  components.selects.slice(0, 5).forEach((sel, i) => {
    const label = sanitize(sel.label || sel.name || `select-${i}`);
    lines.push(`  test('Dropdown: "${label}" – has selectable options', async ({ page }) => {`);
    lines.push(`    const dropdown = page.locator(${jsString(sel.selector)}).first();`);
    lines.push(`    await dropdown.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
    lines.push(`    const isVisible = await dropdown.isVisible().catch(() => false);`);
    lines.push(`    if (!isVisible) { test.skip(); return; }`);
    lines.push(`    const count = await dropdown.locator('option').count();`);
    lines.push(`    expect(count, 'Dropdown should have at least one option').toBeGreaterThan(0);`);
    if (sel.options.length > 1) {
      const opt = sanitize(sel.options[1]);
      lines.push(`    await dropdown.selectOption({ label: ${jsString(opt)} }).catch(() => {});`);
    }
    lines.push(`  });`);
    lines.push(``);
  });

  // ── 4. Checkbox Tests ─────────────────────────────────────────────────────
  components.checkboxes.slice(0, 5).forEach((cb, i) => {
    const label = sanitize(cb.label || cb.name || `checkbox-${i}`);
    lines.push(`  test('Checkbox: "${label}" – can be toggled', async ({ page }) => {`);
    lines.push(`    const checkbox = page.locator(${jsString(cb.selector)}).first();`);
    lines.push(`    await checkbox.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
    lines.push(`    const isVisible = await checkbox.isVisible().catch(() => false);`);
    lines.push(`    if (!isVisible) { test.skip(); return; }`);
    lines.push(`    await checkbox.check();`);
    lines.push(`    expect(await checkbox.isChecked()).toBe(true);`);
    lines.push(`    await checkbox.uncheck();`);
    lines.push(`    expect(await checkbox.isChecked()).toBe(false);`);
    lines.push(`  });`);
    lines.push(``);
  });

  // ── 5. Navigation Tests ───────────────────────────────────────────────────
  if (components.navLinks.length > 0 || components.buttons.length > 0) {
    lines.push(`  // ── 3.2 Navigation Check ──────────────────────────────────`);

    components.navLinks.slice(0, 8).forEach((link, i) => {
      const text = sanitize(link.text || `link-${i}`);
      const href = link.href;
      lines.push(`  test('Nav link: "${text}" – navigates without errors', async ({ page }) => {`);
      lines.push(`    const link = page.locator(${jsString(link.selector)}).first();`);
      lines.push(`    await link.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
      lines.push(`    const isVisible = await link.isVisible().catch(() => false);`);
      lines.push(`    if (!isVisible) { test.skip(); return; }`);
      lines.push(`    const [response] = await Promise.all([`);
      lines.push(`      page.waitForNavigation({ timeout: 10000 }).catch(() => null),`);
      lines.push(`      link.click(),`);
      lines.push(`    ]);`);
      lines.push(`    const status = response ? response.status() : 200;`);
      lines.push(`    expect(status, 'Navigation should not return error').toBeLessThan(400);`);
      lines.push(`  });`);
      lines.push(``);
    });

    // Broken links check
    lines.push(`  test('Link integrity – no broken links on page', async ({ page }) => {`);
    lines.push(`    const links = await page.locator('a[href]').all();`);
    lines.push(`    const brokenLinks = [];`);
    lines.push(`    for (const link of links.slice(0, 20)) {`);
    lines.push(`      const href = await link.getAttribute('href').catch(() => null);`);
    lines.push(`      if (!href || href.startsWith('#') || href.startsWith('javascript:')) continue;`);
    lines.push(`      const fullUrl = href.startsWith('http') ? href : new URL(href, BASE_URL).href;`);
    lines.push(`      try {`);
    lines.push(`        const resp = await page.request.head(fullUrl, { timeout: 8000 });`);
    lines.push(`        if (resp.status() >= 400) brokenLinks.push({ url: fullUrl, status: resp.status() });`);
    lines.push(`      } catch (e) { brokenLinks.push({ url: fullUrl, error: e.message }); }`);
    lines.push(`    }`);
    lines.push(`    if (brokenLinks.length > 0) console.warn('Broken links:', JSON.stringify(brokenLinks, null, 2));`);
    lines.push(`    expect(brokenLinks.length, \`\${brokenLinks.length} broken link(s) found\`).toBe(0);`);
    lines.push(`  });`);
    lines.push(``);
  }

  // ── 6. Button Tests ───────────────────────────────────────────────────────
  components.buttons.slice(0, 6).forEach((btn, i) => {
    const text = sanitize(btn.text || btn.id || `button-${i}`);
    lines.push(`  test('Button: "${text}" – is visible and clickable', async ({ page }) => {`);
    lines.push(`    const btn = page.locator(${jsString(btn.selector)}).first();`);
    lines.push(`    await btn.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});`);
    lines.push(`    const isVisible = await btn.isVisible().catch(() => false);`);
    lines.push(`    if (!isVisible) { test.skip(); return; }`);
    lines.push(`    const isEnabled = await btn.isEnabled().catch(() => false);`);
    lines.push(`    expect(isEnabled, 'Button should be enabled').toBe(true);`);
    lines.push(`  });`);
    lines.push(``);
  });

  // ── 7. Spelling test ──────────────────────────────────────────────────────
  lines.push(`  // ── 3.3 Spelling & Grammar ────────────────────────────────`);
  lines.push(`  test('Spelling – common typos not present in page text', async ({ page }) => {`);
  lines.push(`    const commonTypos = [`);
  lines.push(`      'teh', 'recieve', 'occured', 'seperate', 'definately',`);
  lines.push(`      'adress', 'beleive', 'comming', 'dissapear', 'wierd',`);
  lines.push(`    ];`);
  lines.push(`    const bodyText = await page.locator('body').innerText();`);
  lines.push(`    const lowerText = bodyText.toLowerCase();`);
  lines.push(`    const found = commonTypos.filter(typo => {`);
  lines.push(`      const regex = new RegExp(\`\\\\b\${typo}\\\\b\`);`);
  lines.push(`      return regex.test(lowerText);`);
  lines.push(`    });`);
  lines.push(`    if (found.length > 0) console.warn('Possible typos found:', found);`);
  lines.push(`    // Log as advisory – not a hard failure`);
  lines.push(`    expect(found, \`Possible typos: \${found.join(', ')}\`).toHaveLength(0);`);
  lines.push(`  });`);
  lines.push(``);

  lines.push(`  test('Labels & buttons – no empty text content', async ({ page }) => {`);
  lines.push(`    const emptyButtons = await page.locator('button:visible').filter({ hasText: /^\\s*$/ }).count();`);
  lines.push(`    expect(emptyButtons, 'No visible buttons should have empty labels').toBe(0);`);
  lines.push(`    const emptyLabels = await page.locator('label:visible').filter({ hasText: /^\\s*$/ }).count();`);
  lines.push(`    expect(emptyLabels, 'No visible labels should be empty').toBe(0);`);
  lines.push(`  });`);
  lines.push(``);

  lines.push(`}); // end describe`);
  lines.push(``);

  return lines.join('\n');
}

// ── Value helpers ──────────────────────────────────────────────────────────────
function getValidValue(type) {
  const map = {
    email: 'testuser@example.com',
    password: 'SecurePass123!',
    tel: '+1-555-123-4567',
    url: 'https://example.com',
    number: '42',
    date: '2024-06-15',
    time: '10:30',
    search: 'test query',
    text: 'Sample valid input text',
    default: 'Test Input Value',
  };
  return map[type] || map.default;
}

function getInvalidValue(type) {
  const map = {
    email: 'not-a-valid@@email##',
    tel: 'abc-not-phone',
    url: 'not a url at all!!',
    number: 'abc',
    date: '99/99/9999',
    default: '!!invalid$$',
  };
  return map[type] || map.default;
}

module.exports = { generatePlaywrightScript };
